### ISSUE TITLE
bonjour les charluts

### ISSUE THREAD

**Issue by Becelhi** [datalab-greta/Camille_Alexandre_Becelhi_Projet_3#4]
pirtsmldfkxvb, onksm("ùZMKGDS,;FB ,KPTEHQORÙZGDS;V!:C,LXMJVIPÙEML,G;D,WVJKMBÙXFMLHNSG,DQHR;S,FDJMVCOHIPB ML,FSTQGRSNLDMJIXVPÙOBKML,HET;QZLEKFQJPBOKML ,FGNDSHRQKLJPONL,MG

**Comment by Gerikk** [comment]
Coin!

**Comment by Becelhi** [comment]
CACA BOUDIN
